// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe3RfCQwOcibkcAdJcYcxTK82Ee-_4ztY',
    appId: '1:75997641919:web:0eb37b193c9fbbb7979a0a',
    messagingSenderId: '75997641919',
    projectId: 'homedemo-808db',
    authDomain: 'homedemo-808db.firebaseapp.com',
    storageBucket: 'homedemo-808db.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC94pkzRaJ6dKVHI3INMA-PZTisVn-STF4',
    appId: '1:75997641919:android:e69ac0c7e4e25a10979a0a',
    messagingSenderId: '75997641919',
    projectId: 'homedemo-808db',
    storageBucket: 'homedemo-808db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoiPU_i_S6eHMrNjyG881za6qgMuELv-k',
    appId: '1:75997641919:ios:56b37916c7009ccc979a0a',
    messagingSenderId: '75997641919',
    projectId: 'homedemo-808db',
    storageBucket: 'homedemo-808db.appspot.com',
    iosBundleId: 'com.example.homeapp',
  );
}
